spring:
  flyway:
    enabled: true
    locations: classpath:db/migration/local
    baseline-on-migrate: true
    out-of-order: false
  datasource:
    url: jdbc:postgresql://localhost:5432/customer
    username: admin
    password: pass
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true

server:
  port: 8083

logging:
  level:
    root: debug
    db: debug
    org.springframework.web: debug
    org.hibernate: error
